### ISSUE TITLE
CSS bugs

### ISSUE THREAD

**Issue by laouinia** [laouinia/wi21-cse110-lab3#2]
Please report any CSS bugs
In line 95 the width of the .textBox should be 85% and not %80
could you please check it out. 

Thank you

```css

.textBox{
   color: rgb(0, 0, 0);
   font-size: 25px;
   text-justify: auto;
   background-color: rgb(185, 180, 180);
   margin: 10px 10px 10px 10px;
   display: block;
  margin-left: auto;
  margin-right: auto;
  width: 80%;
    
}
````
